---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "team4-a"
  namespace: "default"
  labels:
    app: "team4-a"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "team4-a"
  template:
    metadata:
      labels:
        app: "team4-a"
    spec:
      containers:
      - name: "onlinesale-sha256-1"
        image: "gcr.io/cap1-339903/github.com/pavithracherukuri/onlinesale@sha256:42d0bbd30cd48a486a937a8e3e018f5d4ae4a26f05e0a17884c96274e4dd04f0"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "team4-a-hpa-lqbk"
  namespace: "default"
  labels:
    app: "team4-a"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "team4-a"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80

